### ISSUE TITLE
Unable to connect to the shadowsocks server through the Beltelecom provider

### ISSUE THREAD

**Issue by roman82101** [brahma-dev/ufw-bots#2]
Hello, the situation is this: ufw-bots is installed on a server with shadowsocks on Ubuntu 20.04, everything works in the city, and when I come to another place where the Beltelecom provider is, I can’t connect to the server. After removing the ipv4 rules (Clearing old ipv4 rules), I managed to connect.
Please tell me how can I find the rule that blocks access to the server

**Comment by brahma-dev** [comment]
It looks like Beltelecom is assigning you IPs that are on the list. All the IPv4 subsets are in [files/ipv4.txt](https://raw.githubusercontent.com/brahma-dev/ufw-bots/master/files/ipv4.txt).
Let me know which subnet you're falling in and I can try to figure if it's a false positive.

**Comment by roman82101** [comment]
Now such an IP 37.212.7.22

**Comment by brahma-dev** [comment]
I should have explained better. It is a list of IP subnets (groups of IPs). Your IP is blocked, if you search for `37.212.0.0` you'll see the line that blocked it.

Unfortunately, these IPs are shared with datacentres so I cannot remove it from the list. For your purpose, you can use the [manual method](https://github.com/brahma-dev/ufw-bots#manually-download-the-script-and-run) and edit the file to remove those IPs before running the script. You can remove all rules starting with `37.212.xx.xx`.

**Comment by roman82101** [comment]
Thank you for your help
